name: "[CI] Driver Test"
run-name: ${{ format('[CI] Driver Test (PR \#{0})', github.event.pull_request.number) }}

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - open
      - reopen
      - synchronize

jobs:
  test_driver_sqlite:
    name: Driver Test - SQLite
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Build & Install package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        make pkg
    - name: Run test
      run: |
        python tests/drivers/sqlite.py
