name: Weekly Release

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    environment: BuildPyPi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in the last week
        id: check_changes
        run: |
          if git log --since='1 week ago' --oneline | grep .
          then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi
      
      - name: Get the date
        id: date
        if: steps.check_changes.outputs.changes == 'true'
        run: echo "::set-output name=date::$(date +'%y%m%d')"

      - name: Get Version Name
        id: version_name
        run: echo "::set-output name=v::$(python ../../test/tools/get_versoin_name.py)"
      - name: Update Version Name
        run: sed -i "s/^version\s*=\s*['\"].*['\"]$/version = '${{ steps.version_name.outputs.v }}.${{ steps.date.outputs.date }}'/" setup.py

      - name: Create Release
        id: create_release
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version_name.outputs.v }}.${{ steps.date.outputs.date }}
          release_name: Weekly Release (${{ steps.date.outputs.date }})
          body: |
            Weekly Release of v${{ steps.version_name.outputs.v }}${{ steps.date.outputs.date }}.
          draft: false
          prerelease: true

