name: CI - Driver Test

run-name: ${{ format('[CI] Driver Test (PR \#{0})', github.event.pull_request.number) }}

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - open
      - reopen
      - synchronize

jobs:
  test_driver_sqlite:
    name: Driver Test - SQLite
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Build & Install package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        make pkg
    - name: Run test
      run: |
        python tests/drivers/sqlite.py

  test_driver_mysql:
    name: Driver Test - MySQL
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Build & Install package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        make pkg
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: ''
        mysql root password: 'root'
    - name: Wait for MySQL to start
      run: |
        sleep 20
    - name: Run test
      run: |
        python tests/drivers/mysql_.py root root
    
