on:
  workflow_dispatch:
  push:
  pull_request_target:
    types:
      - open
      - reopen
      - synchronize

jobs:
  test_driver_sqlite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test
      run: |
        python tests/drivers/sqlite.py

  test_driver_mysql-connector:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: ''
        mysql user: 'test'
        mysql password: 'test'
    - name: Run test
      run: |
        echo "GRANT ALL PRIVILEGES ON test.* TO 'test'@'%'; FLUSH PRIVILEGES;" | mysql -h 127.0.0.1 -P 3306 -u root -p
        sleep 20
        python tests/drivers/mysql_connector.py
    
